"""Add game_id to placed_bets

Revision ID: 135213db5f75
Revises: 0f7bb5e554f3
Create Date: 2025-05-16 22:42:47.427594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135213db5f75'
down_revision = '0f7bb5e554f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_placed_bets_game_id', 'active_bets', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_placed_bets_game_id', type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
