"""Add event_outcome to Bet model

Revision ID: 34353288073e
Revises: 9dc6298ae321
Create Date: 2025-05-03 13:04:05.621371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34353288073e'
down_revision = '9dc6298ae321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('event_outcome', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('event_outcome')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
