"""Add Bet model

Revision ID: 402a4bbad9d7
Revises: d67dafba076d
Create Date: 2025-05-03 08:12:47.484096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402a4bbad9d7'
down_revision = 'd67dafba076d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('bet_type', sa.String(length=50), nullable=False),
    sa.Column('stake_amount', sa.Float(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('potential_winnings', sa.Float(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    # ### end Alembic commands ###
