"""Bet updated

Revision ID: 42220913397f
Revises: ee9232141fd8
Create Date: 2025-05-05 03:13:54.871819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42220913397f'
down_revision = 'ee9232141fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_stake_amount', sa.Float(), nullable=False))
        batch_op.drop_column('stake_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stake_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_column('max_stake_amount')

    # ### end Alembic commands ###
