"""Add privacy column to Post model

Revision ID: 476d7e8fd3a5
Revises: 2ddf354a5a29
Create Date: 2025-05-16 07:57:40.669477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476d7e8fd3a5'
down_revision = '2ddf354a5a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    with op.batch_alter_table('active_bets', schema=None) as batch_op:
        batch_op.alter_column('bet_type_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('max_stake',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               type_=sa.Interval(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placed_bets_scheduled_time'), ['scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_placed_bets_status'), ['status'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('privacy')

    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placed_bets_status'))
        batch_op.drop_index(batch_op.f('ix_placed_bets_scheduled_time'))

    with op.batch_alter_table('active_bets', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.Interval(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('max_stake',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('bet_type_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('bet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('bet_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('odds', sa.FLOAT(), nullable=False),
    sa.Column('potential_winnings', sa.FLOAT(), nullable=False),
    sa.Column('scheduled_time', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('actual_winnings', sa.FLOAT(), nullable=True),
    sa.Column('date_settled', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('event_outcome', sa.VARCHAR(length=50), nullable=True),
    sa.Column('max_stake_amount', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
