"""empty message

Revision ID: 62fb0afc1fdd
Revises: 476d7e8fd3a5
Create Date: 2025-05-16 10:05:59.759906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fb0afc1fdd'
down_revision = '476d7e8fd3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.alter_column('privacy',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_constraint('fk_post_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_post_author_id', 'user', ['author_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_reply_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_reply_author_id', 'user', ['author_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_reply_user', 'user', ['author'], ['id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_post_user', 'user', ['author'], ['id'])
        batch_op.alter_column('privacy',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
