"""Update Bet model

Revision ID: 9dc6298ae321
Revises: 402a4bbad9d7
Create Date: 2025-05-03 08:33:43.227609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc6298ae321'
down_revision = '402a4bbad9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_winnings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date_settled', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('date_settled')
        batch_op.drop_column('actual_winnings')

    # ### end Alembic commands ###
