"""User update

Revision ID: a070250aad95
Revises: d583bf9b6ee7
Create Date: 2025-05-05 02:03:48.906943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a070250aad95'
down_revision = 'd583bf9b6ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_currency'), ['currency'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_currency'))
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
