"""Added new ActiveBets db

Revision ID: b892089d947f
Revises: 42220913397f
Create Date: 2025-05-05 03:44:07.030497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b892089d947f'
down_revision = '42220913397f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('bet_type', sa.String(length=50), nullable=False),
    sa.Column('stake_amount', sa.Float(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_bet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('bet_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('odds', sa.FLOAT(), nullable=False),
    sa.Column('potential_winnings', sa.FLOAT(), nullable=False),
    sa.Column('scheduled_time', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('actual_winnings', sa.FLOAT(), nullable=True),
    sa.Column('date_settled', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('event_outcome', sa.VARCHAR(length=50), nullable=True),
    sa.Column('max_stake_amount', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('active_bets')
    # ### end Alembic commands ###
