"""Add event_outcome to PlacedBets

Revision ID: bf4575a6d45d
Revises: d7385bbc35eb
Create Date: 2025-05-09 10:38:26.697307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4575a6d45d'
down_revision = 'd7385bbc35eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_outcome', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.drop_column('event_outcome')

    # ### end Alembic commands ###
