"""Updated User model with password hashing and relationships

Revision ID: fc430c88d83e
Revises: 33878ef30ca2
Create Date: 2025-05-08 19:54:58.763377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc430c88d83e'
down_revision = '33878ef30ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_password')
        batch_op.drop_index('ix_user_username')
        # Add explicit names for unique constraints
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')  # Use the explicit name
        batch_op.drop_constraint('uq_user_email', type_='unique')  # Use the explicit name
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.create_index('ix_user_password', ['password'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=1)
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=25),
               nullable=True)

    # ### end Alembic commands ###
